const REGULAR_TYPE = 'regular';
const NEW_TYPE = 'new';
const CHILDREN_TYPE = 'children';

const REGULAR_MOVIE_POINTS = 1;
const NEW_MOVIE_PRICE_PER_DAY = 3.0;
const CHILDREN_MOVIE_POINTS = 1;

module.exports = {
  REGULAR_MOVIE_POINTS,
  REGULAR_TYPE,
  NEW_TYPE,
  NEW_MOVIE_PRICE_PER_DAY,
  CHILDREN_TYPE,
  CHILDREN_MOVIE_POINTS
}
